<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_btn btn-primary btn-lg</name>
   <tag></tag>
   <elementGuidId>85f3eb4e-32b0-4260-8f0a-bd44d74f31d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb7b679f-8ac9-41cc-909f-e3a020696677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fbf458bb-8fe0-4345-a7d7-84202a6d2754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg</value>
      <webElementGuid>d5cc2387-38d5-4ae4-bb24-1b527fab49ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>381f94e2-889e-475c-84b1-fca3141c4fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id2</value>
      <webElementGuid>e7cb58ec-543c-4453-af49-9b82fedea187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Background&quot;]/div[@class=&quot;row d-flex justify-content-center align-items-center h-100 px-5&quot;]/div[@class=&quot;col-12 col-md-9 col-lg-7 col-xl-6&quot;]/section[@class=&quot;shadow-lg bg-light rounded align-middle&quot;]/div[@class=&quot;container-fluid h-custom&quot;]/div[@class=&quot;row d-flex justify-content-center align-items-center h-100&quot;]/div[@class=&quot;col-md-8 col-lg-6 col-xl-4 offset-xl-1&quot;]/form[1]/div[@class=&quot;text-center text-lg-start mt-4 pt-2&quot;]/input[@class=&quot;btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>3c3058db-4340-4eb6-9199-5f8669ccb161</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Login']</value>
      <webElementGuid>8554bb68-d95d-454b-8fdd-251987dc2bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>23748768-80d1-4b36-9f99-52e417cd8972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>9764518f-2f5b-4198-b298-bb992b57abac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
