<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_item_1</name>
   <tag></tag>
   <elementGuidId>6be76b20-4422-437a-990a-fd2f9dfe1644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[2]/div/div/div[2]/div[1]/div[1]/div[1]/h6[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>fddcb2fc-1200-44c1-943d-a286e419547c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-0</value>
      <webElementGuid>9ae3bf03-256a-421f-a096-ac6aba42c0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fried Egg</value>
      <webElementGuid>d5035c2c-7c83-412a-bcd8-c3a073152c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-dialog-scrollable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container-fluid row&quot;]/div[@class=&quot;container-fluid row mt-3&quot;]/div[@class=&quot;media-body col-8&quot;]/h6[@class=&quot;mt-0&quot;]</value>
      <webElementGuid>b27901ef-f9b1-4230-9279-e1cdfc2a2e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cartModal']/div/div/div[2]/div/div[3]/div/h6</value>
      <webElementGuid>4f5e9d36-1034-4cc9-9450-316ac7863b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orange Juice'])[1]/following::h6[2]</value>
      <webElementGuid>f0869edd-b2bd-49a2-88c6-e340cc2d91dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omelet'])[1]/following::h6[4]</value>
      <webElementGuid>b0577563-034b-407f-a807-690df866c797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schnitzel'])[1]/preceding::h6[2]</value>
      <webElementGuid>20739542-084c-44b5-8c0b-bd64790700bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fried Egg']/parent::*</value>
      <webElementGuid>a6f4c1d6-5ec8-41ee-8c58-c224cea84c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h6</value>
      <webElementGuid>22b19604-aede-431d-9f3b-33dc26d6bd8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Fried Egg' or . = 'Fried Egg')]</value>
      <webElementGuid>ed81defc-2756-4bea-9a55-3a7c662bcd13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
