<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_btn btn-primary btn-lg</name>
   <tag></tag>
   <elementGuidId>cde24036-97db-44dd-ae07-06d94a1066b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfae3e73-c19b-471b-aa82-9051bf03ab64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f537fbc2-7cb2-496b-b6f1-f6070251386a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg</value>
      <webElementGuid>edb29f5b-a296-4c6b-904d-41e5a9c8ab7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>46ff8c76-3445-40f4-9a92-db5f13251d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id2</value>
      <webElementGuid>1747083c-3460-4021-9947-5a86bc4b0777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Background&quot;]/div[@class=&quot;row d-flex justify-content-center align-items-center h-100 px-5&quot;]/div[@class=&quot;col-12 col-md-9 col-lg-7 col-xl-6&quot;]/section[@class=&quot;shadow-lg bg-light rounded align-middle&quot;]/div[@class=&quot;container-fluid h-custom&quot;]/div[@class=&quot;row d-flex justify-content-center align-items-center h-100&quot;]/div[@class=&quot;col-md-8 col-lg-6 col-xl-4 offset-xl-1&quot;]/form[1]/div[@class=&quot;text-center text-lg-start mt-4 pt-2&quot;]/input[@class=&quot;btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>e4d0c561-f2d1-4141-8d35-e4e6071c5383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Login']</value>
      <webElementGuid>e961868b-760a-4004-a4c8-7c486d22fb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>4943c185-a5d5-444a-b7f8-d6af95e855c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>693092db-8861-4bbe-b940-0c675fded748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
