<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Getsu_navbar-toggler-icon</name>
   <tag></tag>
   <elementGuidId>372543bb-8a96-4b88-9979-c8aa5f102491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navbar-toggler-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc1c09ba-6703-444b-bc88-1a333bc190ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-toggler-icon</value>
      <webElementGuid>b0a118a6-2bf9-4260-9255-a77a7397cfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;d-flex flex-column min-vh-100&quot;]/nav[@class=&quot;navbar navbar-expand-xl navbar-dark bg-danger&quot;]/button[@class=&quot;navbar-toggler&quot;]/span[@class=&quot;navbar-toggler-icon&quot;]</value>
      <webElementGuid>5e4a6eac-150e-4939-8fd2-39d6c57bfbdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>d78117cb-d72f-4fb5-a99d-1ab5435a69d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
