<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_userInput</name>
   <tag></tag>
   <elementGuidId>25601b11-c8e8-40d4-bd1b-63da19c64ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4e06a09-7577-4d94-a31d-ea7168c76876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5054c9bd-4c4e-4a19-a4af-03ce344c7a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userInput</value>
      <webElementGuid>2cc45521-1302-4641-baf9-89964083d0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userInput</value>
      <webElementGuid>1f9f5aa5-a3ca-4e14-b851-e8a6836f59bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>00f70365-7ee0-4872-a294-eb27488b0d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email or username</value>
      <webElementGuid>5fd80ac1-fa8f-4d6f-a5ab-d5a6bf1f4889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userInput&quot;)</value>
      <webElementGuid>65f6c2f5-1024-47b3-afab-403923babc3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userInput']</value>
      <webElementGuid>fad12709-4115-4d6c-8299-ca72f4bc714d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>10d69d82-7a3c-482e-8ac7-74a239ccf221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'userInput' and @name = 'userInput' and @placeholder = 'email or username']</value>
      <webElementGuid>b03e184a-6e6e-4f2a-84bc-fb091b56784d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
